@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

InternshipBook *-right-> "1" UniqueInternshipList

UniqueInternshipList -right-> Internship


Internship *--> "1" CompanyName
Internship *--> "1" Role
Internship *--> "1" ApplicationStatus
Internship *--> "1" StartDate
Internship *--> "1" Duration
Internship *--> "1" Deadline
Internship *--> "*" Requirement
@enduml
