@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

package Logic as LogicPackage {
Class "<<interface>>\nInternshipLogic" as InternshipLogic
Class InternshipLogicManager
}

package Model as ModelPackage {
Class "<<interface>>\nInternshipModel" as InternshipModel
Class InternshipModelManager
}

package Storage as StoragePackage {
Class "<<interface>>\nInternshipStorage" as InternshipStorage
Class InternshipStorageManager
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> InternshipLogic

InternshipLogicManager .up.|> InternshipLogic
InternshipModelManager .up.|> InternshipModel
InternshipStorageManager .up.|> InternshipStorage

InternshipLogicManager --> InternshipModel
InternshipLogicManager --> InternshipStorage
@enduml
