@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Internship Entry Storage Stage

package "Storage" {
    class InternshipStorage as "InternshipStorage"
}

class InternshipEntry as "InternshipEntry:\nJane Street, Coffee maker"

InternshipStorage -[hidden]right-> InternshipEntry

hide InternshipEntry

class Internship as "Internship"

InternshipStorage - Internship : stores >

@enduml
