@startuml
!pragma layout smetana
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Command Parsing Stage

package "Internship Book" {
    class InternshipBookParser as "InternshipBookParser"
}

package "Command" {
    class FilterCommand as "FilterCommand"
}

InternshipBookParser -[hidden]right-> FilterCommand

hide FilterCommand

class UserInput as "User Input: filter ro/jane"

UserInput -down-> InternshipBookParser : parses

@enduml
