@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":InternshipLogicManager" as InternshipLogicManager LOGIC_COLOR
participant ":InternshipBookParser" as InternshipBookParser LOGIC_COLOR
participant ":FilterCommandParser" as FilterCommandParser LOGIC_COLOR
participant "f:FilterCommand" as FilterCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":InternshipModel" as Model MODEL_COLOR
end box

[-> InternshipLogicManager : execute("filter c/citadel")
activate InternshipLogicManager

InternshipLogicManager -> InternshipBookParser : parseCommand("filter c/citadel")
activate InternshipBookParser

create FilterCommandParser
InternshipBookParser -> FilterCommandParser
activate FilterCommandParser

FilterCommandParser --> InternshipBookParser
deactivate FilterCommandParser

InternshipBookParser -> FilterCommandParser : parse("filter c/citadel")
activate FilterCommandParser

create FilterCommand
FilterCommandParser -> FilterCommand
activate FilterCommand

FilterCommand --> FilterCommandParser : f
deactivate FilterCommand

FilterCommandParser --> InternshipBookParser : f
deactivate FilterCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FilterCommandParser -[hidden]-> InternshipBookParser
destroy FilterCommandParser

InternshipBookParser --> InternshipLogicManager : f
deactivate InternshipBookParser

InternshipLogicManager -> FilterCommand : execute(model)
activate FilterCommand
FilterCommand -> Model : updateFilteredInternshipList(predicate), setFilterParameter(filterParameter), setFilterValue(filterValue)
activate Model

Model --> FilterCommand
deactivate Model

create CommandResult
FilterCommand -> CommandResult
activate CommandResult

CommandResult --> FilterCommand
deactivate CommandResult

FilterCommand --> InternshipLogicManager : result
deactivate FilterCommand

[<--InternshipLogicManager
deactivate InternshipLogicManager
@enduml
