@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Filter Command Execution Stage

package "Internship Book" {
    class InternshipLogicManager as "InternshipLogicManager"
    class InternshipStorage as "InternshipStorage"
}

package "Command" {
    class FilterCommand as "FilterCommand"
}

InternshipLogicManager -down-> FilterCommand : executes
FilterCommand -right-> InternshipStorage : filters based on criteria

@enduml
