@startuml
!pragma layout smetana
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyInternshipBook" as ReadOnlyInternshipBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class InternshipBook
Class ModelManager
Class UserPrefs

Class UniqueInternshipList
Class Internship
Class ApplicationStatus
Class CompanyName
Class Role
Class Requirement
Class StartDate
Class Duration
Class Deadline

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

InternshipBook .up.|> ReadOnlyInternshipBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyInternshipBook
ModelManager -left-> "1" InternshipBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

InternshipBook *--> "1" UniqueInternshipList
UniqueInternshipList --> "~* all" Internship
Internship *--> "1" CompanyName
Internship *--> "1" Role
Internship *--> "1" ApplicationStatus
Internship *--> "1" StartDate
Internship *--> "1" Deadline
Internship *--> "1" Duration
Internship *--> "*" Requirement

Internship -[hidden]up--> I
UniqueInternshipList -[hidden]right-> I

ModelManager --> "~* filtered" Internship
@enduml
