@startuml
!pragma layout smetana
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Command Parsing Stage

package "Parser" {
    class InternshipBookParser as "InternshipBookParser"
}

package "Command" {
    class ModifyCommand as "ModifyCommand"
}

InternshipBookParser -[hidden]right-> ModifyCommand

hide ModifyCommand

class UserInput as "modify 1 c/Jane Street ro/Backend Developer"

UserInput -up- InternshipBookParser : < parses

@enduml
