@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Command Execution Stage

package "Internship Book" {
    class InternshipLogicManager as "InternshipLogicManager"
    class InternshipStorage as "InternshipStorage"
}

package "Command" {
    class ModifyCommand as "ModifyCommand"
}

InternshipLogicManager -down- ModifyCommand : > executes
ModifyCommand -up- InternshipStorage : < checks for duplicates\nand replaces original copy with edited one if unique

@enduml
