@startuml

object "InternshipList" as IL {
  internships: [Internship3, Internship1, Internship2]
  currentComparator: BY_ROLE
}

object "Internship3" as I3 {
  companyName: "Optiver"
  role: "Algorithm Engineer"
}

object "Internship1" as I1 {
  companyName: "Citadel"
  role: "Site Reliability Engineer"
}

object "Internship2" as I2 {
  companyName: "Jane Street"
  role: "Software Engineer"
}

IL -down-> I3
IL -down-> I1
IL -down-> I2

@enduml
