@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package InternshipStorage as StoragePackage {

package "InternshipUserPrefs Storage" #F4F6F6{
Class "<<interface>>\nInternshipUserPrefsStorage" as UserPrefsStorage
Class JsonInternshipUserPrefsStorage
}

Class "<<interface>>\nInternshipStorage" as InternshipStorage
Class InternshipStorageManager

package "InternshipBook Storage" #F4F6F6{
Class "<<interface>>\nInternshipBookStorage" as InternshipBookStorage
Class JsonInternshipBookStorage
Class JsonSerializableInternshipBook
Class JsonAdaptedInternship
Class JsonAdaptedRequirement
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> InternshipStorage

InternshipStorageManager .up.|> InternshipStorage
InternshipStorageManager -up-> "1" UserPrefsStorage
InternshipStorageManager -up-> "1" InternshipBookStorage

InternshipStorage -left-|> UserPrefsStorage
InternshipStorage -right-|> InternshipBookStorage

JsonInternshipUserPrefsStorage .up.|> UserPrefsStorage
JsonInternshipBookStorage .up.|> InternshipBookStorage
JsonInternshipBookStorage ..> JsonSerializableInternshipBook
JsonSerializableInternshipBook --> "*" JsonAdaptedInternship
JsonAdaptedInternship --> "*" JsonAdaptedRequirement

@enduml
