@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class InternshipMainWindow
Class HelpWindow
Class ResultDisplay
Class InternshipListPanel
Class InternshipCard
Class StatusBarFooter
Class CommandBox
Class PredicateComparatorDisplay
}

package InternshipModel <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package InternshipLogic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class "<<interface>>\nComandExecuter" as CommandExecuter

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" InternshipMainWindow
InternshipMainWindow *-down->  "1" CommandBox
InternshipMainWindow *-down-> "1" ResultDisplay
InternshipMainWindow *-down-> "1" InternshipListPanel
InternshipMainWindow *-down-> "1" StatusBarFooter
InternshipMainWindow *-down-> "1" PredicateComparatorDisplay
InternshipMainWindow --> "0..1" HelpWindow

InternshipListPanel -down-> "*" InternshipCard

InternshipMainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
InternshipListPanel --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

CommandBox ..> CommandExecuter
InternshipCard ..> InternshipModel
CommandExecuter ..> InternshipLogic
UiManager -right-> InternshipLogic
InternshipMainWindow -left-> InternshipLogic

InternshipListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- HelpWindow
ResultDisplay -[hidden]left- StatusBarFooter

InternshipMainWindow -[hidden]-|> UiPart
@enduml
